df <- read.csv('shidouhou.csv', head=T)
print(df$method)
hist(df$psych_test)
dev.off()
print(sum(10,13,8,15,8))
test_a <- c(10,13,8,15,8)
print(test_a)
print(sum(test_a))
print(sum(test_a)/length(test_a))
print(mean(test_a))
print(median(test_a))
print(table(test_a))
sd <- sum((test_a - mean(test_a))^2)/length(test_a)
print(sd)
print(sqrt(sd))
print(sd(test_a))
norm <- (test_a - mean(test_a)) / sd(test_a)
print(norm)
print(mean(norm))
print(sd(norm))
deviation <- norm * 10 + 50
print(mean(deviation))
print(sd(deviation))
